### PR TITLE
Add tests to expanding of arrays

### PR DESCRIPTION
**Pull request by yosiat**
For https://github.com/tjmehta/keypather/issues/25

Couldn't find the real issue, so I added tests

### CODE REVIEW

**Comment by tjmehta** [comment]
Awesome! Will fix this weekend

**Comment by yosiat** [comment]
@tjmehta thanks!
btw, be careful with `should.eq` because  `{ 0: 'yosi' }.should.eq(['yosi'])` will pass.

**Comment by tjmehta** [comment]
This ended up being more complex than anticipated. I actually have a rewrite in the works, where I wrote a proper keypath parser. I should be able to release the rewrite soon (matter of weeks), and will make sure this test case is satisfied.

**Comment by tjmehta** [comment]
Hey I know it's been a while. I just wanted to follow up and let you know I just finished implementing keypather@2.0.0, and this problem will be resolve. I should be publishing it tonight once I finish the docs and changelog

**Comment by tjmehta** [comment]
published keypather@v3.0.0 lmk if you still have problems

**Pull request closed without merging**
