### PR TITLE
Feature/readme updates

### PR DESCRIPTION
**Pull request by justsml**
@tomekwi requested changes RE: #7

### CODE REVIEW

**Comment by stoeffel** [comment]
@justsml you should [squash][1] your commits to one. 
It's kind of strange to see 50b55ce in this PR.

[1]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by justsml** [comment]
Updated... 
Thanks for the help + guidance here @stoeffel

**Comment by stoeffel** [comment]
@justsml :+1: NP

**Comment by tjmehta** [comment]
Thanks!

**Pull request merged**
